version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
      args:
        - DB_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
